[package]
name = "hwh-rs-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
chrono = "0.4.44"
chrono-tz = "0.10.4"
env_logger = "0.11.9"
futures = "0.3.32"
log = "0.4.29"
mongodb = "3.5.1"
poise = "0.6.1"
regex = "1.12.3"
reqwest = { version = "0.12.28", features = ["stream"] }
songbird = { git = "https://github.com/serenity-rs/songbird", rev = "25195877c715e08df25eda668df6b3a6bb3d3cdf" }
symphonia = { version = "0.5.5", features = ["wav"] }
tokio = { version = "1.50.0", default-features = false, features = ["rt-multi-thread"] }
url = "2.5.3"
